### ISSUE TITLE
Casing Issue

### ISSUE THREAD

**Issue by BenHall** [cpswan/katacoda-scenarios#1]
It looks like the capitalised directory name is causing us some problems.  I renamed it to `iac-part-1-git` and it now loads correctly. I tested it with https://www.katacoda.com/cpswan/scenarios/iac-part-1-git which is why you may have noticed the two URLs for a short time

I've raised an issue and I'll get it fixed on our side.

**Comment by cpswan** [comment]
thanks - it took me a while to figure it out myself by trial and error - one of those times when you wished you'd paid closer attention to email :0
